services:
  application:
    image: anti-hate-discord-app:latest
    container_name: anti-hate-discord-app-bot
    build: .
    environment: ['NODE_ENV=${NODE_ENV:-development}']
    depends_on:
      tests:
        condition: service_completed_successfully
    links: [cassandra, ollama]
    ports: ['3000:3000']
  tests:
    build:
      dockerfile: __tests__/Dockerfile
      context: .
    container_name: anti-hate-discord-app-tests
    volumes: ['.:/application']
    environment: ['NODE_ENV=${NODE_ENV:-test}', 'ENV_FILE=${ENV_FILE:-.env.dev}']
    depends_on:
      cassandra:
        condition: service_healthy
      ollama:
        condition: service_healthy
    links: [cassandra, ollama]
    ports: ['3000:3000']
  cassandra:
    container_name: anti-hate-discord-app-cassie
    image: cassandra:latest
    ports: ['9042:9042']
    healthcheck:
      test: sh -c "cqlsh -e 'describe keyspaces' | grep -x 'anti_hate_discord_bot' | head -c 21"
      interval: 30s
      timeout: 5s
      retries: 3
  ollama:
    container_name: anti-hate-discord-app-ollama
    build: src/ollama
    environment: ['ANALYSIS_MODEL=${ANALYSIS_MODEL:-gemma3:1b}'] # Default to gemma3:1b
    ports: ['11434:11434']
    volumes: ['ollama-data:/root/.ollama']
    healthcheck:
      test: sh /root/.ollama/healthcheck.sh
      interval: 1m
      timeout: 5s
      retries: 3
volumes:
    ollama-data:
