services:
  application:
    image: anti-hate-discord-app:latest
    container_name: anti-hate-discord-bot
    build: .
    environment: ['NODE_ENV=${NODE_ENV}']
    depends_on:
      # application-tests:
      #   condition: service_completed_successfully
      cassandra:
        condition: service_healthy
      ollama:
        condition: service_healthy
    # links: [application-tests, cassandra, ollama]
    links: [cassandra, ollama]
    ports: ['3000:3000']
    restart: on-failure
  # application-tests:
  #   build:
  #     dockerfile: ./tests/Dockerfile
  #     context: .
  #   container_name: anti-hate-discord-bot-tests
  #   volumes:
  #     - .:/application
  #   environment: ['NODE_ENV=${NODE_ENV:-test}']
  cassandra:
    container_name: anti-hate-cassie-db
    image: cassandra:latest
    ports: ['9042:9042']
    healthcheck:
      test: sh -c "cqlsh -e 'describe keyspaces' | grep -x 'anti_hate_discord_bot' | head -c 21"
      interval: 30s
      timeout: 5s
      retries: 3
  ollama:
    container_name: anti-hate-ollama-service
    build: ./src/ollama
    environment: ['ANALYSIS_MODEL=${ANALYSIS_MODEL:-gemma3:1b}'] # Default to gemma3:1b
    ports: ['11434:11434']
    volumes: ['ollama-data:/root/.ollama']
    healthcheck:
      test: sh /root/.ollama/healthcheck.sh
      interval: 1m
      timeout: 5s
      retries: 3
volumes:
    ollama-data:
