services:
  application:
    image: anti-hate-discord-app:latest
    container_name: anti-hate-discord-bot
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
    command: sh -c "pnpm install && pnpm build && pnpm run deploy"
    depends_on:
      cassandra:
        condition: service_healthy
    links: [cassandra]
    ports: ['3000:3000', '11434:11434']
    restart: always
  cassandra:
    container_name: anti-hate-cassie-db
    image: cassandra:latest
    ports: ['9042:9042']
    healthcheck:
      test: sh -c "cqlsh -e 'describe keyspaces' | grep 'anti_hate_discord_bot' | head -c 21"
      interval: 30s
      timeout: 10s
      retries: 3
